---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system
  name: istio-system
spec:
  finalizers:
  - kubernetes
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-mesh
  namespace: istio-system
spec:
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: {{.Values.clusterName}}
      network: network1
